name: Build & Test

on:
  push:
    branches: ['main']
    paths-ignore:
      - '*.md'
  pull_request:
    branches: ['main']
    paths-ignore:
      - '*.md'

jobs:
  publish:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js & configure npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Activate Yarn 4
        run: |
              corepack enable
              corepack prepare yarn@4.9.2 --activate

      - name: Install dependencies
        run: yarn install --immutable --immutable-cache

      - name: Run lint and tests
        run: yarn lint && yarn test

      - name: Build all packages
        run: yarn build

      - name: Bundle all packages
        run: yarn bundle
