name: Build & Publish

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'When you press run workflow, the npm package will be published.'
        default: 'I understand.'

jobs:
  publish:
    name: Build, Test & Publish
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js & configure npm
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'
          scope: '@logpot'

      - name: Activate Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run lint and tests
        run: yarn lint && yarn test

      - name: Build all packages
        run: yarn build

      - name: Bundle all packages
        run: yarn bundle

      - name: Bundle all packages
        run: yarn package

      - name: Publish each workspace
        # Publishes every non-private package under packages/*
        run: yarn workspaces foreach --all --topological --no-private npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
